"""Add map coordinates to fixed_point_steps

Revision ID: 41c7562bec15
Revises: ca0c8ae5dbe4
Create Date: 2025-07-15 23:33:20.697463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c7562bec15'
down_revision: Union[str, Sequence[str], None] = 'ca0c8ae5dbe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixed_point_steps', sa.Column('position_x', sa.Float(), nullable=True))
    op.add_column('fixed_point_steps', sa.Column('position_y', sa.Float(), nullable=True))
    op.add_column('fixed_point_steps', sa.Column('skill_position_x', sa.Float(), nullable=True))
    op.add_column('fixed_point_steps', sa.Column('skill_position_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixed_point_steps', 'skill_position_y')
    op.drop_column('fixed_point_steps', 'skill_position_x')
    op.drop_column('fixed_point_steps', 'position_y')
    op.drop_column('fixed_point_steps', 'position_x')
    # ### end Alembic commands ###
